AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Instance with Security Group

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: test
      ImageId: ami-067d1e60475437da2 # Amazon Linux 2 AMI (replace  your desired AMI ID)

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EC2 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Open SSH access from anywhere (for demonstration, you should restrict this in a production environment)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Open HTTP access from anywhere (for demonstration, you should restrict this in a production environment)

Outputs:
  InstanceId:
    Description: Instance ID of the EC2 instance
    Value: !Ref MyEC2Instance
  PublicDnsName:
    Description: Public DNS name of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicDnsName
